---
# handlers file for setup_apache
- name: Start httpd service
  service:
    name: httpd
    state: started

- name: Start apache2 service
  service:
    name: apache2
    state: started

- name: Restart httpd service
  service:
    name: httpd
    state: restarted

- name: Restart apache2 service
  service:
    name: apache2
    state: restarted
